module.exports = {
  ROLES: {
    ADMIN: 'ADMIN',
    EXECUTIVE: 'EXECUTIVE',
    DIRECTOR: 'DIRECTOR',
    MANAGER: 'MANAGER',
    SALESMAN: 'SALESMAN',
  },
  
  LEAD_STATUS: {
    NEW: 'NEW',
    CONTACTED: 'CONTACTED',
    INTERESTED: 'INTERESTED',
    NOT_INTERESTED: 'NOT_INTERESTED',
    SITE_VISIT: 'SITE_VISIT',
    NEGOTIATION: 'NEGOTIATION',
    DOCUMENTATION: 'DOCUMENTATION',
    WON: 'WON',
    LOST: 'LOST',
  },
  
  LEAD_SOURCE: {
    WEBSITE: 'WEBSITE',
    REFERRAL: 'REFERRAL',
    INSTAGRAM: 'INSTAGRAM',
    YOUTUBE: 'YOUTUBE',
    EMAIL: 'EMAIL',
    WHATSAPP: 'WHATSAPP',
    NINETY_NINE_ACRES: 'NINETY_NINE_ACRES',
    MAGICBRICKS: 'MAGICBRICKS',
    OLX: 'OLX',
    COLD_OUTREACH: 'COLD_OUTREACH',
    WALK_IN: 'WALK_IN',
  },
  
  PRIORITY: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    URGENT: 'URGENT',
  },
  
  ACTIVITY_TYPE: {
    CALL: 'CALL',
    EMAIL: 'EMAIL',
    MEETING: 'MEETING',
    NOTE: 'NOTE',
    TASK: 'TASK',
    FOLLOW_UP: 'FOLLOW_UP',
  },
  
  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    INTERNAL_SERVER_ERROR: 500,
  },
};
