module.exports = {
  ROLES: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    USER: 'USER',
  },
  
  LEAD_STATUS: {
    NEW: 'NEW',
    CONTACTED: 'CONTACTED',
    QUALIFIED: 'QUALIFIED',
    PROPOSAL: 'PROPOSAL',
    NEGOTIATION: 'NEGOTIATION',
    WON: 'WON',
    LOST: 'LOST',
    INACTIVE: 'INACTIVE',
  },
  
  LEAD_SOURCE: {
    WEBSITE: 'WEBSITE',
    REFERRAL: 'REFERRAL',
    SOCIAL_MEDIA: 'SOCIAL_MEDIA',
    EMAIL_CAMPAIGN: 'EMAIL_CAMPAIGN',
    COLD_CALL: 'COLD_CALL',
    EVENT: 'EVENT',
    PARTNER: 'PARTNER',
    OTHER: 'OTHER',
  },
  
  PRIORITY: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    URGENT: 'URGENT',
  },
  
  ACTIVITY_TYPE: {
    CALL: 'CALL',
    EMAIL: 'EMAIL',
    MEETING: 'MEETING',
    NOTE: 'NOTE',
    TASK: 'TASK',
    FOLLOW_UP: 'FOLLOW_UP',
  },
  
  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    INTERNAL_SERVER_ERROR: 500,
  },
};
